# Form implementation generated from reading ui file 'f:\2. Coding\3. VS Code Project\Python\music_player_qt\ui\app.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_App(object):
    def setupUi(self, App):
        App.setObjectName("App")
        App.resize(800, 600)
        self.gridLayout = QtWidgets.QGridLayout(App)
        self.gridLayout.setObjectName("gridLayout")
        self.search_button = QtWidgets.QPushButton(App)
        self.search_button.setMinimumSize(QtCore.QSize(0, 30))
        self.search_button.setObjectName("search_button")
        self.gridLayout.addWidget(self.search_button, 0, 0, 1, 1)
        self.other_menu = QtWidgets.QWidget(App)
        self.other_menu.setMinimumSize(QtCore.QSize(160, 0))
        self.other_menu.setStyleSheet("QWidget {\n"
"}")
        self.other_menu.setObjectName("other_menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.other_menu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.download_from_url_button = QtWidgets.QPushButton(self.other_menu)
        self.download_from_url_button.setObjectName("download_from_url_button")
        self.verticalLayout.addWidget(self.download_from_url_button)
        self.setting_button = QtWidgets.QPushButton(self.other_menu)
        self.setting_button.setObjectName("setting_button")
        self.verticalLayout.addWidget(self.setting_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.other_menu, 2, 0, 1, 1)
        self.search_bar = QtWidgets.QLineEdit(App)
        self.search_bar.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.search_bar.setFont(font)
        self.search_bar.setObjectName("search_bar")
        self.gridLayout.addWidget(self.search_bar, 0, 1, 1, 1)
        self.playback_control = QtWidgets.QWidget(App)
        self.playback_control.setMinimumSize(QtCore.QSize(0, 80))
        self.playback_control.setMaximumSize(QtCore.QSize(16777215, 80))
        self.playback_control.setStyleSheet("QWidget {\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.playback_control.setObjectName("playback_control")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.playback_control)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout.addWidget(self.playback_control, 3, 0, 1, 2)
        self.main_menu = QtWidgets.QWidget(App)
        self.main_menu.setObjectName("main_menu")
        self.gridLayout.addWidget(self.main_menu, 2, 1, 1, 1)

        self.retranslateUi(App)
        QtCore.QMetaObject.connectSlotsByName(App)

    def retranslateUi(self, App):
        _translate = QtCore.QCoreApplication.translate
        App.setWindowTitle(_translate("App", "Music Player"))
        self.search_button.setText(_translate("App", "Search"))
        self.download_from_url_button.setText(_translate("App", "Download from URL"))
        self.setting_button.setText(_translate("App", "Settings"))
        self.search_bar.setPlaceholderText(_translate("App", "Search songs here...."))
