# Form implementation generated from reading ui file 'f:\2. Programming\3. VS Code Project\Python\music_player_qt\ui\download_from_url_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DownloadFromURL(object):
    def setupUi(self, DownloadFromURL):
        DownloadFromURL.setObjectName("DownloadFromURL")
        DownloadFromURL.resize(303, 86)
        self.gridLayout = QtWidgets.QGridLayout(DownloadFromURL)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.url_edit = MyLineEdit(DownloadFromURL)
        self.url_edit.setObjectName("url_edit")
        self.gridLayout.addWidget(self.url_edit, 0, 1, 1, 1)
        self.link_label = QtWidgets.QLabel(DownloadFromURL)
        self.link_label.setObjectName("link_label")
        self.gridLayout.addWidget(self.link_label, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(DownloadFromURL)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.download_button = QtWidgets.QPushButton(self.frame)
        self.download_button.setObjectName("download_button")
        self.horizontalLayout.addWidget(self.download_button)
        self.cancel_button = QtWidgets.QPushButton(self.frame)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 2)

        self.retranslateUi(DownloadFromURL)
        QtCore.QMetaObject.connectSlotsByName(DownloadFromURL)

    def retranslateUi(self, DownloadFromURL):
        _translate = QtCore.QCoreApplication.translate
        DownloadFromURL.setWindowTitle(_translate("DownloadFromURL", "Download From URL"))
        self.link_label.setText(_translate("DownloadFromURL", "Video Link:"))
        self.download_button.setText(_translate("DownloadFromURL", "Download!"))
        self.cancel_button.setText(_translate("DownloadFromURL", "Exit"))
from my_widget import MyLineEdit
