# Form implementation generated from reading ui file 'f:\2. Programming\3. VS Code Project\Python\music_player_qt\ui\music_setting.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MusicSetting(object):
    def setupUi(self, MusicSetting):
        MusicSetting.setObjectName("MusicSetting")
        MusicSetting.resize(650, 156)
        self.gridLayout = QtWidgets.QGridLayout(MusicSetting)
        self.gridLayout.setObjectName("gridLayout")
        self.browse_button = QtWidgets.QPushButton(MusicSetting)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout.addWidget(self.browse_button, 0, 3, 1, 1)
        self.author_label = QtWidgets.QLabel(MusicSetting)
        self.author_label.setObjectName("author_label")
        self.gridLayout.addWidget(self.author_label, 2, 0, 1, 2)
        self.thumbnail_path = QtWidgets.QLineEdit(MusicSetting)
        self.thumbnail_path.setObjectName("thumbnail_path")
        self.gridLayout.addWidget(self.thumbnail_path, 0, 2, 1, 1)
        self.title = QtWidgets.QLineEdit(MusicSetting)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 1, 2, 1, 2)
        self.author = QtWidgets.QLineEdit(MusicSetting)
        self.author.setObjectName("author")
        self.gridLayout.addWidget(self.author, 2, 2, 1, 2)
        self.current_multiplier = QtWidgets.QSlider(MusicSetting)
        self.current_multiplier.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.current_multiplier.setObjectName("current_multiplier")
        self.gridLayout.addWidget(self.current_multiplier, 3, 2, 1, 2)
        self.thumbnail_label = QtWidgets.QLabel(MusicSetting)
        self.thumbnail_label.setObjectName("thumbnail_label")
        self.gridLayout.addWidget(self.thumbnail_label, 0, 0, 1, 2)
        self.current_multiplier_label = QtWidgets.QLabel(MusicSetting)
        self.current_multiplier_label.setObjectName("current_multiplier_label")
        self.gridLayout.addWidget(self.current_multiplier_label, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(MusicSetting)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.title_label = QtWidgets.QLabel(MusicSetting)
        self.title_label.setObjectName("title_label")
        self.gridLayout.addWidget(self.title_label, 1, 0, 1, 2)
        self.widget = QtWidgets.QWidget(MusicSetting)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_button = QtWidgets.QPushButton(self.widget)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(self.widget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.gridLayout.addWidget(self.widget, 4, 0, 1, 4)

        self.retranslateUi(MusicSetting)
        QtCore.QMetaObject.connectSlotsByName(MusicSetting)

    def retranslateUi(self, MusicSetting):
        _translate = QtCore.QCoreApplication.translate
        MusicSetting.setWindowTitle(_translate("MusicSetting", "Settings"))
        self.browse_button.setText(_translate("MusicSetting", "Browse"))
        self.author_label.setText(_translate("MusicSetting", "Author"))
        self.thumbnail_label.setText(_translate("MusicSetting", "Thumbnail"))
        self.current_multiplier_label.setText(_translate("MusicSetting", "1.0"))
        self.label.setText(_translate("MusicSetting", "Current Volume Multiplier:"))
        self.title_label.setText(_translate("MusicSetting", "Title"))
        self.ok_button.setText(_translate("MusicSetting", "OK"))
        self.cancel_button.setText(_translate("MusicSetting", "Cancel"))
