# Form implementation generated from reading ui file 'f:\2. Programming\3. VS Code Project\Python\music_player_qt\ui\playlist_ui.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PlaylistWidget(object):
    def setupUi(self, PlaylistWidget):
        PlaylistWidget.setObjectName("PlaylistWidget")
        PlaylistWidget.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(PlaylistWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.playlist = Playlist(PlaylistWidget)
        self.playlist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.playlist.setRowCount(0)
        self.playlist.setColumnCount(3)
        self.playlist.setObjectName("playlist")
        item = QtWidgets.QTableWidgetItem()
        self.playlist.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.playlist.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.playlist.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.playlist)

        self.retranslateUi(PlaylistWidget)
        QtCore.QMetaObject.connectSlotsByName(PlaylistWidget)

    def retranslateUi(self, PlaylistWidget):
        _translate = QtCore.QCoreApplication.translate
        PlaylistWidget.setWindowTitle(_translate("PlaylistWidget", "Form"))
        item = self.playlist.horizontalHeaderItem(0)
        item.setText(_translate("PlaylistWidget", "Thumbnail"))
        item = self.playlist.horizontalHeaderItem(1)
        item.setText(_translate("PlaylistWidget", "Title"))
        item = self.playlist.horizontalHeaderItem(2)
        item.setText(_translate("PlaylistWidget", "Author"))
from my_widget import Playlist
