# Form implementation generated from reading ui file 'f:\2. Programming\3. VS Code Project\Python\music_player_qt\ui\playlist_ui.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MusicListWidget(object):
    def setupUi(self, MusicListWidget):
        MusicListWidget.setObjectName("MusicListWidget")
        MusicListWidget.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(MusicListWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.music_list = MusicList(MusicListWidget)
        self.music_list.setRowCount(0)
        self.music_list.setColumnCount(3)
        self.music_list.setObjectName("music_list")
        item = QtWidgets.QTableWidgetItem()
        self.music_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.music_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.music_list.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.music_list)

        self.retranslateUi(MusicListWidget)
        QtCore.QMetaObject.connectSlotsByName(MusicListWidget)

    def retranslateUi(self, MusicListWidget):
        _translate = QtCore.QCoreApplication.translate
        MusicListWidget.setWindowTitle(_translate("MusicListWidget", "Form"))
        item = self.music_list.horizontalHeaderItem(0)
        item.setText(_translate("MusicListWidget", "Thumbnail"))
        item = self.music_list.horizontalHeaderItem(1)
        item.setText(_translate("MusicListWidget", "Title"))
        item = self.music_list.horizontalHeaderItem(2)
        item.setText(_translate("MusicListWidget", "Author"))


from my_widget import MusicList
