# Form implementation generated from reading ui file 'f:\2. Coding\3. VS Code Project\Python\music_player_qt\ui\search_menu.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SearchMenu(object):
    def setupUi(self, SearchMenu):
        SearchMenu.setObjectName("SearchMenu")
        SearchMenu.resize(646, 466)
        self.verticalLayout = QtWidgets.QVBoxLayout(SearchMenu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searching_label = QtWidgets.QLabel(SearchMenu)
        self.searching_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.searching_label.setObjectName("searching_label")
        self.verticalLayout.addWidget(self.searching_label)
        self.results = QtWidgets.QTableWidget(SearchMenu)
        self.results.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.results.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.results.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.results.setRowCount(0)
        self.results.setColumnCount(3)
        self.results.setObjectName("results")
        item = QtWidgets.QTableWidgetItem()
        self.results.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.results.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.results.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.results)

        self.retranslateUi(SearchMenu)
        QtCore.QMetaObject.connectSlotsByName(SearchMenu)

    def retranslateUi(self, SearchMenu):
        _translate = QtCore.QCoreApplication.translate
        SearchMenu.setWindowTitle(_translate("SearchMenu", "Form"))
        self.searching_label.setText(_translate("SearchMenu", "Searching..."))
        item = self.results.horizontalHeaderItem(0)
        item.setText(_translate("SearchMenu", "Title"))
        item = self.results.horizontalHeaderItem(1)
        item.setText(_translate("SearchMenu", "Channel"))
        item = self.results.horizontalHeaderItem(2)
        item.setText(_translate("SearchMenu", "Download"))
