# Form implementation generated from reading ui file 'f:\2. Coding\3. VS Code Project\Python\music_player_qt\ui\welcome_menu.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WelcomeMenu(object):
    def setupUi(self, WelcomeMenu):
        WelcomeMenu.setObjectName("WelcomeMenu")
        WelcomeMenu.resize(646, 466)
        self.verticalLayout = QtWidgets.QVBoxLayout(WelcomeMenu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.greetings = QtWidgets.QLabel(WelcomeMenu)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.greetings.setFont(font)
        self.greetings.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.greetings.setObjectName("greetings")
        self.verticalLayout.addWidget(self.greetings)
        self.label = QtWidgets.QLabel(WelcomeMenu)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.help_button = QtWidgets.QPushButton(WelcomeMenu)
        self.help_button.setMinimumSize(QtCore.QSize(0, 50))
        self.help_button.setObjectName("help_button")
        self.verticalLayout.addWidget(self.help_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(WelcomeMenu)
        QtCore.QMetaObject.connectSlotsByName(WelcomeMenu)

    def retranslateUi(self, WelcomeMenu):
        _translate = QtCore.QCoreApplication.translate
        WelcomeMenu.setWindowTitle(_translate("WelcomeMenu", "Form"))
        self.greetings.setText(_translate("WelcomeMenu", "Greetings"))
        self.label.setText(_translate("WelcomeMenu", "Welcome to my youtube based music player!"))
        self.help_button.setText(_translate("WelcomeMenu", "Help"))
