# Form implementation generated from reading ui file 'f:\2. Coding\3. VS Code Project\Python\music_player_qt\ui\welcome_menu.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WelcomeMenu(object):
    def setupUi(self, WelcomeMenu):
        WelcomeMenu.setObjectName("WelcomeMenu")
        WelcomeMenu.resize(646, 466)
        self.verticalLayout = QtWidgets.QVBoxLayout(WelcomeMenu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.greetings = QtWidgets.QLabel(WelcomeMenu)
        self.greetings.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.greetings.setObjectName("greetings")
        self.verticalLayout.addWidget(self.greetings)

        self.retranslateUi(WelcomeMenu)
        QtCore.QMetaObject.connectSlotsByName(WelcomeMenu)

    def retranslateUi(self, WelcomeMenu):
        _translate = QtCore.QCoreApplication.translate
        WelcomeMenu.setWindowTitle(_translate("WelcomeMenu", "Form"))
        self.greetings.setText(_translate("WelcomeMenu", "Greetings"))
